export const PLUGIN_TICKERS = [
  "ABB", "ACC", "ADANIENT", "ADANIGREEN", "ADANIPORTS", "ADANIPOWER", "ALKEM", "AMBUJACEM",
  "APOLLOHOSP", "ASIANPAINT", "ASTRAL", "AUROPHARMA", "AXISBANK", "BAJAJFINSV", "BAJAJHLDNG",
  "BAJFINANCE", "BANDHANBNK", "BANKBARODA", "BERGEPAINT", "BHARTIARTL", "BOSCHLTD", "BRITANNIA",
  "CHOLAFIN", "CIPLA", "COALINDIA", "COLPAL", "CONCOR", "DABUR", "DIVISLAB", "DLF", "DRREDDY",
  "EICHERMOT", "FEDERALBNK", "GAIL", "GODREJCP", "GRASIM", "HAVELLS", "HCLTECH", "HDFCAMC",
  "HDFCBANK", "HDFCLIFE", "HEROMOTOCO", "HINDALCO", "HINDUNILVR", "HINDZINC", "ICICIBANK",
  "ICICIGI", "ICICIPRULI", "INDIGO", "INDUSTOWER", "INFY", "ITC", "JINDALSTEL", "JSWENERGY",
  "JSWSTEEL", "KOTAKBANK", "LICI", "LTIM", "LUPIN", "MARICO", "MARUTI", "MOTHERSON", "MRF",
  "MUTHOOTFIN", "NESTLEIND", "NMDC", "NTPC", "OIL", "ONGC", "PAGEIND", "PIIND", "PIDILITIND", "PNB",
  "POWERGRID", "RECLTD", "SBILIFE", "SBIN", "SHREECEM", "SIEMENS", "SRF", "SUNPHARMA", "TATACHEM",
  "TATACONSUM", "TATAELXSI", "TATAPOWER", "TATASTEEL", "TCS", "TORNTPHARM", "TORNTPOWER", "TRENT",
  "TVSMOTOR", "UBL", "ULTRACEMCO", "VEDL", "WIPRO",
].sort();

export interface TradingStockDraft {
  symbol: string;
  capital: string;
  stop_loss: number;
}

export interface TradingConfigurationDraft {
  candle: string;
  strategy: string;
  useBrokerCash: boolean;
  stocks: TradingStockDraft[];
}

/** Auto-generated alpha allocation rows from saved-configuration.alphas.symbols */
export interface AutoGeneratedSymbol {
  symbol: string;
  capital: number;
  stop_loss: number;
  rank?: number;
  role?: string;
  base_multiplier?: number;
}

export interface AlphasInfo {
  configName?: string;
  date?: string;
  symbols: AutoGeneratedSymbol[];
}

export const createEmptyStockDraft = (): TradingStockDraft => ({
  symbol: '', capital: '', stop_loss: 5,
});

export const createDefaultConfig = (): TradingConfigurationDraft => ({
  candle: '5m', strategy: 'A', useBrokerCash: true,
  stocks: [createEmptyStockDraft()],
});

export const validateConfig = (
  draft: TradingConfigurationDraft,
  opts?: { allowEmptyStocks?: boolean; alphas?: AlphasInfo | null },
): string | null => {
  const autoCount = opts?.alphas?.symbols.length ?? 0;
  if (draft.stocks.length === 0) {
    if (opts?.allowEmptyStocks || autoCount > 0) return null;
    return 'Add at least one stock';
  }
  if (draft.stocks.some(s => !s.symbol || !s.capital)) return 'Fill all symbol and capital fields';
  if (draft.stocks.some(s => Number.isNaN(Number(s.capital)) || Number(s.capital) <= 0)) return 'Capital must be > 0';
  if (draft.stocks.some(s => Number.isNaN(s.stop_loss) || s.stop_loss <= 0)) return 'Stop loss must be > 0';
  const symbols = draft.stocks.map(s => s.symbol);
  if (new Set(symbols).size !== symbols.length) return 'Each stock can only be added once';
  return null;
};

export type StartSymbolPayload = {
  symbol: string;
  capital: number;
  stop_loss: number;
};

/**
 * Start / save body: original shape only.
 * When alphas are provided (start trading), auto symbols are appended as
 * symbol / capital / stop_loss — rank, role, base_multiplier stay UI-only.
 */
export const buildPayload = (
  draft: TradingConfigurationDraft,
  alphas?: AlphasInfo | null,
) => {
  const manual: StartSymbolPayload[] = draft.stocks
    .filter(s => s.symbol && s.capital !== '')
    .map(s => ({
      symbol: s.symbol,
      capital: Number(s.capital),
      stop_loss: s.stop_loss / 100,
    }));

  const used = new Set(manual.map(s => s.symbol));
  const auto: StartSymbolPayload[] = (alphas?.symbols ?? [])
    .filter(s => s.symbol && !used.has(s.symbol))
    .map(s => ({
      symbol: s.symbol,
      capital: Number(s.capital),
      // Auto rows are stored as percent in the UI model.
      stop_loss: s.stop_loss / 100,
    }));

  return {
    symbols: [...manual, ...auto],
    use_broker_cash: draft.useBrokerCash,
    candle: draft.candle,
    strategy: draft.strategy,
  };
};

/** Build a start payload from a raw saved-configuration object (manual + alphas). */
export const buildStartPayloadFromConfiguration = (
  raw: Record<string, unknown> | null | undefined,
) => {
  const draft = draftFromConfiguration(raw);
  const alphas = alphasFromConfiguration(raw);
  return buildPayload(draft, alphas);
};

function stopLossToPercent(slRaw: number): number {
  if (!Number.isFinite(slRaw)) return 5;
  return slRaw > 0 && slRaw <= 1 ? slRaw * 100 : slRaw;
}

function parseManualStock(item: unknown): TradingStockDraft | null {
  if (!item || typeof item !== 'object') return null;
  const s = item as Record<string, unknown>;
  const symbol = String(s.symbol ?? s.Symbol ?? '').trim();
  if (!symbol) return null;
  const capitalVal = s.capital ?? s.Capital ?? '';
  const slRaw = Number(s.stop_loss ?? s.stopLoss ?? s.Stop_Loss ?? 5);
  return {
    symbol,
    capital: capitalVal === '' || capitalVal == null ? '' : String(capitalVal),
    stop_loss: stopLossToPercent(slRaw),
  };
}

function parseAutoSymbol(item: unknown): AutoGeneratedSymbol | null {
  if (!item || typeof item !== 'object') return null;
  const s = item as Record<string, unknown>;
  const symbol = String(s.symbol ?? '').trim();
  if (!symbol) return null;
  const capital = Number(s.capital ?? 0);
  const slRaw = Number(s.stop_loss ?? 0.05);
  const rank = s.rank != null ? Number(s.rank) : undefined;
  const base_multiplier = s.base_multiplier != null ? Number(s.base_multiplier) : undefined;
  const role = typeof s.role === 'string' ? s.role : undefined;
  return {
    symbol,
    capital: Number.isFinite(capital) ? capital : 0,
    stop_loss: stopLossToPercent(slRaw),
    rank: Number.isFinite(rank as number) ? rank : undefined,
    role,
    base_multiplier: Number.isFinite(base_multiplier as number) ? base_multiplier : undefined,
  };
}

/** Read auto-generated alpha symbols from a saved configuration blob. */
export const alphasFromConfiguration = (raw: Record<string, unknown> | null | undefined): AlphasInfo | null => {
  if (!raw || typeof raw !== 'object') return null;
  const alphas = raw.alphas;
  if (!alphas || typeof alphas !== 'object') return null;
  const a = alphas as Record<string, unknown>;
  const list = Array.isArray(a.symbols) ? a.symbols : [];
  const symbols = list.map(parseAutoSymbol).filter((s): s is AutoGeneratedSymbol => s != null);
  if (symbols.length === 0) return null;
  return {
    configName: typeof a.config_name === 'string' ? a.config_name : undefined,
    date: typeof a.date === 'string' ? a.date : undefined,
    symbols,
  };
};

/** Hydrate the editable form from manual `symbols` only (not alphas). */
export const draftFromConfiguration = (raw: Record<string, unknown> | null | undefined): TradingConfigurationDraft => {
  const base = createDefaultConfig();
  if (!raw || typeof raw !== 'object') return base;

  const candle = typeof raw.candle === 'string' && raw.candle ? raw.candle : base.candle;
  const strategy = typeof raw.strategy === 'string' && raw.strategy ? raw.strategy : base.strategy;
  const useBrokerCash = typeof raw.use_broker_cash === 'boolean'
    ? raw.use_broker_cash
    : typeof raw.useBrokerCash === 'boolean'
      ? raw.useBrokerCash
      : base.useBrokerCash;

  const symbolsRaw = Array.isArray(raw.symbols)
    ? raw.symbols
    : Array.isArray(raw.stocks)
      ? raw.stocks
      : [];

  const stocks = symbolsRaw
    .map(parseManualStock)
    .filter((s): s is TradingStockDraft => s != null);

  return {
    candle,
    strategy,
    useBrokerCash,
    stocks: stocks.length > 0 ? stocks : base.stocks,
  };
};

const STRATEGY_LABELS: Record<string, string> = {
  A: 'Stoppage Reversal',
  B: 'Exposure Expansion',
};

/** Compact summary for list cards / pickers. */
export const summarizeConfiguration = (raw?: Record<string, unknown> | null) => {
  const draft = draftFromConfiguration(raw);
  const alphas = alphasFromConfiguration(raw ?? null);
  const symbols = draft.stocks.map(s => s.symbol).filter(Boolean);
  return {
    symbolCount: symbols.length,
    symbols,
    autoSymbolCount: alphas?.symbols.length ?? 0,
    autoSymbols: alphas?.symbols.map(s => s.symbol) ?? [],
    alphasConfigName: alphas?.configName,
    candle: draft.candle,
    strategy: draft.strategy,
    strategyLabel: STRATEGY_LABELS[draft.strategy] || draft.strategy,
    useBrokerCash: draft.useBrokerCash,
    totalCapital: draft.stocks.reduce((sum, s) => sum + (Number(s.capital) || 0), 0),
  };
};
